{
 "title": "[Codeworks] Docker and system monitoring prod",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "servergroup", "query": { "query": "label_values(group)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{group=~\"$servergroup\", instance=~\"$instance\"}) by (instance) / sum(node_memory_MemTotal_bytes{group=~\"$servergroup\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{mountpoint=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance) - sum(node_filesystem_free_bytes{mountpoint=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance)) / sum(node_filesystem_size_bytes{mountpoint=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "READ {{instance}}"
    },
    {
     "expr": "- rate(node_disk_written_bytes_total{group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])",
     "legendFormat": "WRITE{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "RECEIVED {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "SENT {{instance}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Number of Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\"^monitor.*\", name!=\"\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"^monitor.*\", name!=\"\", group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) by (instance, name) * 100",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (container_memory_usage_bytes{name=~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"} / on(instance) group_left node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * container_fs_usage_bytes{name=~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"} / container_fs_limit_bytes{name=~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) by (instance, name)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval])) by (instance, name)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  }
 ]
}