{
 "title": "[FTT] 伺服器執行情況報表",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servergroup", "query": { "query": "label_values(group)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Production - CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", group=~\"prd\", instance=~\"$instance\"}[$__interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Production - 記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{group=~\"prd\", instance=~\"$instance\"}) by (instance) / sum(node_memory_MemTotal_bytes{group=~\"prd\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Production - 硬碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"prd\", instance=~\"$instance\"}) by (instance, mountpoint) - sum(node_filesystem_free_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"prd\", instance=~\"$instance\"}) by (instance, mountpoint)) / sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"prd\", instance=~\"$instance\"}) by (instance, mountpoint)",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Production - 硬碟使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{group=~\"prd\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "READ {{instance}}"
    },
    {
     "expr": "-sum(rate(node_disk_written_bytes_total{group=~\"prd\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "WRITE {{instance}}"
    }
   ]
  },
  {
   "title": "Production - 網路使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", group=~\"prd\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "IN {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", group=~\"prd\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "OUT  {{instance}}"
    }
   ]
  },
  { "title": "Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Development - CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", group=~\"dev-01\", instance=~\"$instance\"}[$__interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Development - 記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{group=~\"dev-01\", instance=~\"$instance\"}) by (instance) / sum(node_memory_MemTotal_bytes{group=~\"dev-01\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Development - 硬碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"dev-01\", instance=~\"$instance\"}) by (instance, mountpoint) - sum(node_filesystem_free_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"dev-01\", instance=~\"$instance\"}) by (instance, mountpoint)) / sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"dev-01\", instance=~\"$instance\"}) by (instance, mountpoint)",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Development - 硬碟使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{group=~\"dev-01\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "READ {{instance}}"
    },
    {
     "expr": "-sum(rate(node_disk_written_bytes_total{group=~\"dev-01\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "WRITE {{instance}}"
    }
   ]
  },
  {
   "title": "Development - 網路使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", group=~\"dev-01\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "IN {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", group=~\"dev-01\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "OUT  {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Database - CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", group=~\"db-01\", instance=~\"$instance\"}[$__interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database - 記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{group=~\"db-01\", instance=~\"$instance\"}) by (instance) / sum(node_memory_MemTotal_bytes{group=~\"db-01\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database - 硬碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"db-01\", instance=~\"$instance\"}) by (instance, mountpoint) - sum(node_filesystem_free_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"db-01\", instance=~\"$instance\"}) by (instance, mountpoint)) / sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"db-01\", instance=~\"$instance\"}) by (instance, mountpoint)",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Database - 硬碟使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{group=~\"db-01\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "READ {{instance}}"
    },
    {
     "expr": "-sum(rate(node_disk_written_bytes_total{group=~\"db-01\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "WRITE {{instance}}"
    }
   ]
  },
  {
   "title": "Database - 網路使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", group=~\"db-01\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "IN {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", group=~\"db-01\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "OUT  {{instance}}"
    }
   ]
  }
 ]
}