{
 "title": "[NEW] General Dashboard",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "servergroup", "query": { "query": "label_values(group)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{group=~\"$servergroup\", instance=~\"$instance\"}) by (instance) / sum(node_memory_MemTotal_bytes{group=~\"$servergroup\", instance=~\"$instance\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "硬碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance, mountpoint) - sum(node_filesystem_free_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance, mountpoint)) / sum(node_filesystem_size_bytes{mountpoint=~\"^/($|mnt.*)\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance, mountpoint)",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "硬碟使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "READ {{instance}}"
    },
    {
     "expr": "-sum(rate(node_disk_written_bytes_total{group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "WRITE {{instance}}"
    }
   ]
  },
  {
   "title": "網路使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "RECEIVED {{instance}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\", group=~\"$servergroup\", instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "SENT {{instance}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "容器 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\", name!~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}[$__interval])) by (instance, name) * 100",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "容器記憶體使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(container_memory_usage_bytes{name!=\"\", name!~\"^monitor_.*\", group=~\"$servergroup\", instance=~\"$instance\"})\r\n  by (name, instance)\r\n  /\r\n  sum(clamp_min(container_spec_memory_limit_bytes{name!=\"\", name!~\"^monitor_.*\", group=~\"$servergroup\", instance=~\"$instance\"}, 1))\r\n  by (name, instance)\r\n) AND\r\nsum(\r\n  (container_spec_memory_limit_bytes{name!=\"\", name!~\"^monitor_.*\", group=~\"$servergroup\", instance=~\"$instance\"} > 0)) by (instance, name)\r\n",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "容器硬碟使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, instance) (\r\n  rate(container_fs_reads_bytes_total{\r\n    name!=\"\", \r\n    name!~\"^monitor_.*\", \r\n    group=~\"$servergroup\", \r\n    instance=~\"$instance\"\r\n  }[$__interval])\r\n)\r\n",
     "legendFormat": "READ {{instance}}-{{name}}"
    },
    {
     "expr": "sum by (name, instance) (\r\n  -rate(container_fs_reads_bytes_total{\r\n    name!=\"\", \r\n    name!~\"^monitor_.*\", \r\n    group=~\"$servergroup\", \r\n    instance=~\"$instance\"\r\n  }[$__interval])\r\n)\r\n",
     "legendFormat": "WRITE {{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "容器硬碟使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(container_fs_usage_bytes{name!=\"\", name!~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance, name)\r\n/\r\nsum(container_fs_limit_bytes{name!=\"\", name!~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"}) by (instance, name)\r\n",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "容器網路下載量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (\r\n  rate(container_network_receive_bytes_total{\r\n    name!=\"\", name!~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"\r\n  }[$__interval])\r\n)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "容器網路上傳量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (\r\n  rate(container_network_transmit_bytes_total{\r\n    name!=\"\", name!~\"^monitor.*\", group=~\"$servergroup\", instance=~\"$instance\"\r\n  }[$__interval])\r\n)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  }
 ]
}