version: '3'

services:
  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: monitor_node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
    volumes:
      # - '/:/host:ro,rslave'
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: monitor_cadvisor
    build:
      context: ./
      dockerfile: docker/cadvisor.Dockerfile
    restart: always
    # command: ["--enable_load_reader=true", "--container_hints=/etc/cadvisor/container_hints.json", "--v=4", "--stderrthreshold=0", "--log_dir=/var/log", "--logtostderr=false", "--alsologtostderr=false"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /dev/disk/:/dev/disk:ro
    logging:
      options:
        max-size: "200m"
        max-file: "3"
    #ports:
    #  - 8080:8080
    # ports:
    #  - 9100:9100

  nginx:
    container_name: monitoring_nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./htpasswd:/etc/nginx/basic_auth/.htpasswd
    restart: always

networks:
  default:
    external:
      name: monitor-network