version: '3'

services:
  node-exporter: # default port: 9100
    image: prom/node-exporter:v1.2.2
    container_name: monitor_node_exporter
    restart: always
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    
  cadvisor: # default port: 8080
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: monitor_cadvisor
    restart: always
    # command: ["--enable_load_reader=true", "--container_hints=/etc/cadvisor/container_hints.json", "--v=4", "--stderrthreshold=0", "--log_dir=/var/log", "--logtostderr=false", "--alsologtostderr=false"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /dev/disk/:/dev/disk:ro
    logging:
      options:
        max-size: "200m" # Max size of log file before rotation (200MB)
        max-file: "3" # Keep 3 rotated log files (200MB each)

  nginx:
    container_name: monitor_nginx
    image: nginx:1.26.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/basic_auth/.htpasswd
    restart: always

networks:
  default:    
    name: monitor-target-network
    external: false # docker compose will automatically create and manage this network
