FROM chromedp/headless-shell:latest

# Install necessary fonts for chinese characters in grafana monitor pdf report
RUN apt-get update && apt-get install -y \
    fonts-noto-cjk \
    fonts-wqy-zenhei \
    fonts-wqy-microhei \
    && rm -rf /var/lib/apt/lists/*