apiVersion: 1
contactPoints:
    - orgId: 1
      name: CW_DC_PROD
      receivers:
        - uid: bel9eo1xljvnlf
          type: discord
          settings:
            message: <@&1361166806873800764> {{ template "default.message" . }}
            title: Grafana Alerting - {{ template "default.title" . }}
            url: -
            use_discord_username: true
          disableResolveMessage: false
