global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
      monitor: 'monitor'

scrape_configs:
  # for localhost test
  #- job_name: "prometheus"
  #  static_configs:
  #    - targets: ["localhost:9090"]
      
  #- job_name: "grafana"
  #  static_configs:
  #    - targets: ["grafana:3000"]

  # test-dev
  - job_name: 'node-status'
    basic_auth:
      username: cw
      password: Cw@1423_
    scrape_interval: 5s
    metrics_path: "/node/metrics"
    static_configs:
      # could add more targets here
      # - targets: ['monitor_nginx:80']
      #   labels:
      #     group: 'local'
      #     source: 'node'
      - targets: ['13.114.226.250:8080']
        labels:
          group: 'test-dev'
          source: 'node'
      - targets: ['43.207.59.71:8080']
        labels:
          group: 'test-dev-2'
          source: 'node'
  - job_name: 'docker-status'
    basic_auth:
      username: cw
      password: Cw@1423_
    scrape_interval: 5s
    metrics_path: "/cadvisor/metrics"
    static_configs:
      # could add more targets here
      # - targets: ['monitor_nginx:80']
      #   labels:
      #     group: 'local'
      #     source: 'docker'
      - targets: ['13.114.226.250:8080']
        labels:
          group: 'test-dev'
          source: 'docker'
      - targets: ['43.207.59.71:8080']
        labels:
          group: 'test-dev-2'
          source: 'docker'
